// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Hotel.Data;

#nullable disable

namespace Sistema_Hotel.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240611015254_AdicionandoNumQuarto")]
    partial class AdicionandoNumQuarto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Hotel.Models.QuartoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hospede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumQuarto")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Quartos");
                });
#pragma warning restore 612, 618
        }
    }
}
