// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Hotel.Data;

#nullable disable

namespace Sistema_Hotel.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240612032439_TestingDataBase1")]
    partial class TestingDataBase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Hotel.Models.HospedeModel", b =>
                {
                    b.Property<long>("CPF")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("CPF");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("Sistema_Hotel.Models.QuartoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualCPF")
                        .HasColumnType("int");

                    b.Property<string>("AtualNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOut")
                        .HasColumnType("date");

                    b.Property<int>("NumQuarto")
                        .HasColumnType("int");

                    b.Property<long?>("ObjHospedeCPF")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double?>("Tipo")
                        .HasColumnType("float");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ObjHospedeCPF");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("Sistema_Hotel.Models.QuartoModel", b =>
                {
                    b.HasOne("Sistema_Hotel.Models.HospedeModel", "ObjHospede")
                        .WithMany()
                        .HasForeignKey("ObjHospedeCPF");

                    b.Navigation("ObjHospede");
                });
#pragma warning restore 612, 618
        }
    }
}
